#!/usr/bin/env python3
"""Generate Linux/cp313 hashed lock for Dockerfile.prod.

Downloads manylinux wheels (and py3-none-any) then writes
``requirements-runtime.lock`` with ``--hash=sha256:...`` lines.

    python scripts/lock_runtime_deps.py

Dockerfile installs with::

    pip install --require-hashes -r requirements-runtime.lock
"""
from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "requirements-runtime.txt"
OUT = ROOT / "requirements-runtime.lock"

_PIN_RE = re.compile(r"^([A-Za-z0-9_.\-]+)==([^\s;#]+)")
# PEP 427 wheel: name-version(-build)?-py-abi-platform.whl
_WHEEL_RE = re.compile(
    r"^(?P<name>.+?)-(?P<ver>[^-]+?)(?:-(?P<build>\d[^-]*))?-"
    r"(?P<py>[^-]+)-(?P<abi>[^-]+)-(?P<plat>[^-]+)\.whl$",
    re.I,
)


def _direct_pins() -> list[str]:
    pins: list[str] = []
    for raw in SRC.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        base = line.split(";", 1)[0].strip()
        m = _PIN_RE.match(base)
        if m:
            pins.append(f"{m.group(1)}=={m.group(2)}")
    return pins


def _norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def main() -> int:
    if not SRC.is_file():
        print(f"FAIL: missing {SRC}", file=sys.stderr)
        return 1
    pins = _direct_pins()
    if not pins:
        print("FAIL: no == pins in requirements-runtime.txt", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory() as tmp:
        dldir = Path(tmp)
        cmd = [
            sys.executable,
            "-m",
            "pip",
            "download",
            "--dest",
            str(dldir),
            "--platform",
            "manylinux2014_x86_64",
            "--python-version",
            "313",
            "--implementation",
            "cp",
            "--abi",
            "cp313",
            "--only-binary=:all:",
            *pins,
        ]
        print("+", " ".join(cmd), flush=True)
        subprocess.check_call(cmd)

        # Map normalized name -> list of (pin, hash_line) accumulating hashes
        # for the resolved closure (all downloaded wheels).
        entries: dict[str, dict[str, str]] = {}
        for art in sorted(dldir.iterdir()):
            if not art.is_file() or not art.name.endswith(".whl"):
                continue
            m = _WHEEL_RE.match(art.name)
            if not m:
                print(f"WARN: skip non-standard wheel name {art.name}", flush=True)
                continue
            name = _norm(m.group("name"))
            ver = m.group("ver")
            digest = subprocess.check_output(
                [sys.executable, "-m", "pip", "hash", str(art)], text=True
            )
            h = ""
            for line in digest.splitlines():
                if line.strip().startswith("--hash="):
                    h = line.strip()
                    break
            if not h:
                print(f"FAIL: no hash for {art.name}", file=sys.stderr)
                return 1
            pin = f"{name}=={ver}"
            # Keep canonical package name from pin list when possible
            for p in pins:
                pn, pv = p.split("==", 1)
                if _norm(pn) == name and pv == ver:
                    pin = p
                    break
            entries[pin] = h

        if not entries:
            print("FAIL: no wheels hashed", file=sys.stderr)
            return 1

        # Ensure every direct pin is present
        for p in pins:
            key = None
            pn, pv = p.split("==", 1)
            for ek in entries:
                en, ev = ek.split("==", 1)
                if _norm(en) == _norm(pn) and ev == pv:
                    key = ek
                    break
            if key is None:
                print(f"FAIL: direct pin missing from download: {p}", file=sys.stderr)
                return 1

        lines = [
            "# AUTO-GENERATED by scripts/lock_runtime_deps.py (linux/cp313 manylinux).",
            f"# Source: {SRC.name}",
            "# Install (Docker/Linux): pip install --require-hashes -r requirements-runtime.lock",
            "# Refresh: python scripts/lock_runtime_deps.py",
            "",
        ]
        for pin in sorted(entries, key=lambda s: s.lower()):
            lines.append(f"{pin} \\")
            lines.append(f"    {entries[pin]}")
        OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"OK: wrote {OUT} ({len(entries)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
